### PR TITLE
Add functionality to export trials

### PR DESCRIPTION
**Pull request by jtquach1**
Changes made:
- Displayed a study with its actual likelihood status
- Replicated exporting trials functionality from clinical-trial-matching-engine
  - [unpackResearchStudyResults](https://github.com/mcode/clinical-trial-matching-engine/blob/6fa5e8ec948052282eafe7876675debaf44ec1d5/src/app/export/parse-data.ts#L4-L49), [test](https://github.com/mcode/clinical-trial-matching-engine/blob/6fa5e8ec948052282eafe7876675debaf44ec1d5/src/app/export/parse-data.spec.ts#L16-L206)
  - [exportTrials](https://github.com/mcode/clinical-trial-matching-engine/blob/6fa5e8ec948052282eafe7876675debaf44ec1d5/src/app/export/export-data.ts#L7-L13), [test](https://github.com/mcode/clinical-trial-matching-engine/blob/6fa5e8ec948052282eafe7876675debaf44ec1d5/src/app/export/export-data.spec.ts#L18-L139)
- Refactored results page-related components to take in bundle entries instead of research studies (so match likelihood data can be exported)
- Refactored getStudyProps and getDetails

### CODE REVIEW

**Comment by jtquach1** [comment]
# Demo of current functionality (saving selected vs. all trials)

## Save selected trials
https://user-images.githubusercontent.com/33106214/146849753-35a92e8c-691b-45fa-b269-8bb6ec3aeaf7.mov
[clinicalTrials (1).xlsx](https://github.com/mcode/clinical-trial-matching-app/files/7748659/clinicalTrials.1.xlsx)

## Save all trials (none selected)
https://user-images.githubusercontent.com/33106214/146849800-4b6f89d7-0418-42f2-aada-ce4cc751699c.mov
[clinicalTrials (2).xlsx](https://github.com/mcode/clinical-trial-matching-app/files/7748660/clinicalTrials.2.xlsx)

**Comment by jtquach1** [comment]
# Before memoizing Study and ResultsHeader (delay between saving studies)

https://user-images.githubusercontent.com/33106214/147128673-db6a9dd4-8920-4899-8c1e-567b87ef55db.mov



# After memoizing

https://user-images.githubusercontent.com/33106214/147128683-57c42881-9e89-402b-8dab-8aec504b0460.mov

**Comment by ChristineDuong** [comment]
I am unsure on whether I agree with one of the "smart behaviors". It seems that there is an option to "Export All" if no trials are saved. If a trial is saved, your only option is to export saved trials, so you would have to clear them to Export All. I can go either way on this -- have you discussed this behavior with someone else?

**Comment by jtquach1** [comment]
> I am unsure on whether I agree with one of the "smart behaviors". It seems that there is an option to "Export All" if no trials are saved. If a trial is saved, your only option is to export saved trials, so you would have to clear them to Export All. I can go either way on this -- have you discussed this behavior with someone else? 

Yes, @zlister first suggested the features to Export All trials when no trials are saved, and Export saved trials when at least one trial is saved.

**Review by ChristineDuong — APPROVED** [review]

**Comment by zlister** [comment]
> > I am unsure on whether I agree with one of the "smart behaviors". It seems that there is an option to "Export All" if no trials are saved. If a trial is saved, your only option is to export saved trials, so you would have to clear them to Export All. I can go either way on this -- have you discussed this behavior with someone else?
> 
> Yes, @zlister first suggested the features to Export All trials when no trials are saved, and Export saved trials when at least one trial is saved.

Yes, I think that the way that @jtquach1 implemented this is the way it should work for now.

**Pull request merged**
