### PR TITLE
Add install/test scripts

### PR DESCRIPTION
**Pull request by dmpotter44**
This adds a bunch of scripts designed to automate installing the system within a fresh server install.

### CODE REVIEW

**Review by ChristineDuong — COMMENTED** [review]
Overall, great! Only thing is -- and I don't know if this is out of scope or not worth it -- but does it make sense to have this install process also change the configuration of the app itself to reflect what wrappers were installed? For example, if you've decided that you didn't want to support BCT, should it remove that option from `next.config.js`? Or do we just leave that to the user to sync on their own? (If the latter, we might want to just put a note there to remind users to do that).

Maybe a question for @zlister

**Comment by zlister** [comment]
> Overall, great! Only thing is -- and I don't know if this is out of scope or not worth it -- but does it make sense to have this install process also change the configuration of the app itself to reflect what wrappers were installed? For example, if you've decided that you didn't want to support BCT, should it remove that option from `next.config.js`? Or do we just leave that to the user to sync on their own? (If the latter, we might want to just put a note there to remind users to do that).
> 
> Maybe a question for @zlister

Ultimately, I believe that should be something that is automatically configured to be done in the script itself. Do you feel the same way @dmpotter44?

**Comment by dmpotter44** [comment]
> > Overall, great! Only thing is -- and I don't know if this is out of scope or not worth it -- but does it make sense to have this install process also change the configuration of the app itself to reflect what wrappers were installed? For example, if you've decided that you didn't want to support BCT, should it remove that option from `next.config.js`? Or do we just leave that to the user to sync on their own? (If the latter, we might want to just put a note there to remind users to do that).
> > Maybe a question for @zlister
> 
> Ultimately, I believe that should be something that is automatically configured to be done in the script itself. Do you feel the same way @dmpotter44?

Not the way it presently works, for two reasons. The first is that we currently install a wrapper (Trialjectory) that isn't used by the current Epic front end. The second is that the only way to configure this currently involves modifying a file that's under version control. The way Next.js works is that it wants you to configure things that differ depending on install is via environment variables. Unfortunately, we don't currently use environment variables to determine which wrappers to display in the UI.

If we modified `next.config.js` to generate its configuration based on environment variables, allowing the active wrappers to be selected based on those, then the install script could write the supported wrappers to `.env.local` and not worry about creating potential conflicts for later updates. But the way this currently works, a value hardcoded into `next.config.js`, makes programmatically modifying it difficult and error prone, and would make it potentially break updates by causing a merge conflict against a future update. Having the install script modify `next.config.js` is a bad idea.

Allowing it to write out the supported wrappers is a good idea, but only if it could do it in a file like `.env.local`. This could be something done in a future update, but that probably shouldn't be done by modifying `next.config.js` directly.

**Comment by ChristineDuong** [comment]
> > > Overall, great! Only thing is -- and I don't know if this is out of scope or not worth it -- but does it make sense to have this install process also change the configuration of the app itself to reflect what wrappers were installed? For example, if you've decided that you didn't want to support BCT, should it remove that option from `next.config.js`? Or do we just leave that to the user to sync on their own? (If the latter, we might want to just put a note there to remind users to do that).
> > > Maybe a question for @zlister
> > 
> > 
> > Ultimately, I believe that should be something that is automatically configured to be done in the script itself. Do you feel the same way @dmpotter44?
> 
> Not the way it presently works, for two reasons. The first is that we currently install a wrapper (Trialjectory) that isn't used by the current Epic front end. The second is that the only way to configure this currently involves modifying a file that's under version control. The way Next.js works is that it wants you to configure things that differ depending on install is via environment variables. Unfortunately, we don't currently use environment variables to determine which wrappers to display in the UI.
> 
> If we modified `next.config.js` to generate its configuration based on environment variables, allowing the active wrappers to be selected based on those, then the install script could write the supported wrappers to `.env.local` and not worry about creating potential conflicts for later updates. But the way this currently works, a value hardcoded into `next.config.js`, makes programmatically modifying it difficult and error prone, and would make it potentially break updates by causing a merge conflict against a future update. Having the install script modify `next.config.js` is a bad idea.
> 
> Allowing it to write out the supported wrappers is a good idea, but only if it could do it in a file like `.env.local`. This could be something done in a future update, but that probably shouldn't be done by modifying `next.config.js` directly.

I guess first question is why don't we use TrialJectory with the `epic` branch? Is it because it's not on master? 

That makes sense that it wouldn't modify `next.config.js` directly, but I feel like it's either still worth:
1. Defining all of the possible wrappers in `next.config.js` and then only turning on certain ones (the overalap? Subset?) that are installed. Perhaps this is done via setting an environmental variable. Or --
2. Maybe just for now print out a warning that if the subset of installed wrappers is changed that someone should go look at `next.config.js` in the app to reconfigure it to match? Otherwise there will be errors.

**Comment by zlister** [comment]
> > > > Overall, great! Only thing is -- and I don't know if this is out of scope or not worth it -- but does it make sense to have this install process also change the configuration of the app itself to reflect what wrappers were installed? For example, if you've decided that you didn't want to support BCT, should it remove that option from `next.config.js`? Or do we just leave that to the user to sync on their own? (If the latter, we might want to just put a note there to remind users to do that).
> > > > Maybe a question for @zlister
> > > 
> > > 
> > > Ultimately, I believe that should be something that is automatically configured to be done in the script itself. Do you feel the same way @dmpotter44?
> > 
> > 
> > Not the way it presently works, for two reasons. The first is that we currently install a wrapper (Trialjectory) that isn't used by the current Epic front end. The second is that the only way to configure this currently involves modifying a file that's under version control. The way Next.js works is that it wants you to configure things that differ depending on install is via environment variables. Unfortunately, we don't currently use environment variables to determine which wrappers to display in the UI.
> > If we modified `next.config.js` to generate its configuration based on environment variables, allowing the active wrappers to be selected based on those, then the install script could write the supported wrappers to `.env.local` and not worry about creating potential conflicts for later updates. But the way this currently works, a value hardcoded into `next.config.js`, makes programmatically modifying it difficult and error prone, and would make it potentially break updates by causing a merge conflict against a future update. Having the install script modify `next.config.js` is a bad idea.
> > Allowing it to write out the supported wrappers is a good idea, but only if it could do it in a file like `.env.local`. This could be something done in a future update, but that probably shouldn't be done by modifying `next.config.js` directly.
> 
> I guess first question is why don't we use TrialJectory with the `epic` branch? Is it because it's not on master?
> 
> That makes sense that it wouldn't modify `next.config.js` directly, but I feel like it's either still worth:
> 
> 1. Defining all of the possible wrappers in `next.config.js` and then only turning on certain ones (the overalap? Subset?) that are installed. Perhaps this is done via setting an environmental variable. Or --
> 2. Maybe just for now print out a warning that if the subset of installed wrappers is changed that someone should go look at `next.config.js` in the app to reconfigure it to match? Otherwise there will be errors.

After discussion, a line has been added at the end of the install script to inform the user to go and check the `next.config.js` file and confirm `wrappers.json` contains all of the desired wrappers.

**Review by zlister — APPROVED** [review]

**Review by ChristineDuong — APPROVED** [review]

**Pull request merged**
